function tirarAcentos(palavra){
let novaPalavra = "";
for (let i=0;i<palavra.length;i++){
if (palavra[i] === "á" || palavra[i] === "â" || palavra[i] === "ã"){novaPalavra += "a";}
else if (palavra[i] === "é" || palavra[i] === "ê"){novaPalavra += "e";}
else if (palavra[i] === "í" || palavra[i] === "î"){novaPalavra += "i";}
else if (palavra[i] === "ó" || palavra[i] === "ô" || palavra[i] === "õ"){novaPalavra += "o";}
else if (palavra[i] === "ú" || palavra[i] === "û"){novaPalavra += "u";}
else if (palavra[i] === "ç"){novaPalavra += "c";}
else {novaPalavra += palavra[i];}
}
return novaPalavra;
}

function chutarLetra(entrada){

entrada = entrada.split(",");
letra = entrada[0];
indice = Number(entrada[1]);
let statusAcerto = false;

for (let i=0;i<palavraSecreta.length;i++){
if(letra === palavraSecretaSemAcentos[i]){
document.getElementsByClassName("cabecalho")[i].innerHTML = palavraSecreta[i];
statusAcerto = true;
letrasRestantes--;
}
}

if (!statusAcerto) {tentativas--;}
document.getElementsByClassName("alfabeto")[indice].setAttribute("style","display: none");
if (tentativas > 0){document.getElementsByTagName("h1")[1].innerHTML = `${tentativas}`;}
else {
for (let i=0;i<document.getElementsByClassName("alfabeto").length;i++){
document.getElementsByClassName("alfabeto")[i].setAttribute("style","display: none");
}
document.getElementsByTagName("h1")[0].innerHTML = "Game Over! A palavra era:";
document.getElementsByTagName("h1")[1].innerHTML = palavraSecreta+".";
}

if (letrasRestantes == 0){
for (let i=0;i<document.getElementsByClassName("alfabeto").length;i++){
document.getElementsByClassName("alfabeto")[i].setAttribute("style","display: none");
}
document.getElementsByTagName("h1")[0].innerHTML = "Parabéns! Você acertou a palavra:";
document.getElementsByTagName("h1")[1].innerHTML = palavraSecreta+".";
}

}

const letras3 = ["paz","não","fel","céu","ser","vil","sob","mal","ver","mãe","ter","ego","bem","mas","dom","bom","vir","vão","são","dar","ora","que","era","elo","luz","nós","réu","com","seu","tal","foi","rol","mim","uma","lua","até","hum","por","fim","vis","pós","dor","ato","sol","sem","vez","pai","dia","dou","irá","pro","eis","rua","tez","ler","ode","tão","nem","fiz","ajo","voz","gay","meu","lei","voo","mau","mão","num","dês","afã","pôr","for","rio","daí","olá","cia","lar","jus","sua","fez","ira","via","som","nau","sim","amo","rei","tem","boa","más","uso","mês","jaz","ido","asa","uns","lhe","eco","pal","aia"];
const letras4 = ["amor","fato","mito","viés","você","como","caos","esmo","brio","vide","ação","sede","após","pois","vida","casa","auge","saga","medo","ônus","ermo","suma","vovó","mote","além","sina","tolo","idem","urge","crer","pela","apto","zelo","veio","pude","tudo","mais","ruim","área","amar","rude","coxo","cota","para","soar","ater","será","fase","ente","auto","trás","doce","voga","logo","onde","deus","rima","pelo","ante","cedo","jugo","meio","alma","arte","meta","cujo","sela","traz","numa","cela","teor","sido","noia","face","asco","nojo","alvo","foco","isso","pose","sair","base","vale","ódio","agir","teve","alto","todo","ócio","rito","eita","irão","novo","ágil","alva","tese","alta","bojo","nexo","orla"];
const letras5 = ["sagaz","âmago","negro","termo","êxito","mexer","nobre","senso","afeto","algoz","ética","plena","mútua","tênue","fazer","assim","vigor","sutil","aquém","porém","seção","fosse","sanar","poder","audaz","ideia","cerne","inato","moral","sobre","desde","muito","justo","honra","quiçá","torpe","sonho","razão","fútil","etnia","ícone","anexo","amigo","égide","tange","lapso","haver","expor","mútuo","dengo","tempo","casal","então","hábil","seara","boçal","ávido","ardil","pesar","saber","causa","graça","dizer","genro","óbice","posse","coser","pária","dever","brado","tenaz","prole","sendo","crivo","corja","comum","temor","detém","ainda","ânimo","ápice","ceder","ânsia","estar","pauta","digno","assaz","xibiu","culto","mundo","atroz","fugaz","censo","gleba","forte","vício","vulgo","cozer","valha","denso"];
const letras6 = ["exceto","cínico","idôneo","âmbito","néscio","índole","mister","vereda","apogeu","inócuo","convém","utopia","sádico","escopo","ênfase","idiota","casual","mérito","alusão","hostil","anseio","cético","legado","hétero","pressa","gentil","alheio","nocivo","infame","clichê","paixão","exímio","defina","afável","adorno","dádiva","êxtase","sóbrio","adesão","larica","aferir","astuto","também","otário","sessão","limiar","solene","julgar","glória","lábaro","formal","hábito","apreço","embora","ensejo","ímpeto","eficaz","outrem","ocioso","júbilo","dispor","difuso","alento","perene","nuance","facção","escusa","exílio","cessão","lúdico","abster","ilação","alçada","objeto","acesso","acento","desejo","axioma","sanção","isento","tácito","etéreo","buscar","mulher","cortês","cobiça","mazela","sisudo","penhor","eximir","avidez","receio","vulgar","remoto","prazer","fático","quando","sempre","nômade","asseio"];
const letras7 = ["empatia","aurélio","cônjuge","embuste","exceção","caráter","efêmero","prolixo","verbete","idílico","análogo","genuíno","estória","sublime","família","pêsames","inferir","apático","sucinto","acepção","redimir","astúcia","pródigo","cultura","audácia","estigma","recesso","virtude","refutar","icônico","soberba","estável","cinismo","exortar","mórbido","trivial","mitigar","síntese","aspecto","luxúria","cordial","sucesso","alegria","imputar","escória","emergir","anátema","ademais","candura","orgulho","deboche","excerto","litígio","almejar","através","contudo","frívolo","coragem","saudade","oriundo","alcunha","ambíguo","salutar","austero","amizade","escroto","sensato","quimera","ambição","excesso","racismo","relação","erudito","imersão","fomento","modesto","parcial","colosso","demanda","exótico","ciência","conciso","piedade","volátil","notório","bizarro","isenção","vigente","padecer","híbrido","auferir","intenso","inércia","ansioso","sentido","emotivo","déspota","límpido","profano","difusão"];
const letras8 = ["inerente","respeito","peculiar","denegrir","genocida","anuência","deferido","equidade","prudente","pandemia","iminente","essência","misógino","desgraça","invasivo","alienado","eminente","abstrato","premissa","extensão","empírico","conceito","talarico","ardiloso","ascensão","rapariga","reiterar","lascívia","devaneio","relativo","prodígio","passível","conserto","gratidão","analogia","inserção","modéstia","apologia","ativista","remissão","inóspito","destarte","medíocre","monótono","despeito","fomentar","inefável","respaldo","retórica","concerne","alicerce","sinônimo","proceder","metódico","primazia","perfídia","rechaçar","história","portanto","demagogo","complexo","consiste","critério","notívago","distinto","espectro","sucumbir","abnegado","amálgama","desfecho","singular","suscitar","paradoxo","escárnio","contexto","processo","comunhão","elegível","vocábulo","objetivo","refletir","impávido","maestria","obstante","endêmico","desígnio","problema","jurídico","solícito","instigar","incrível","epifania","redenção","mediante","paralelo","insípido","resoluto","imanente","preceito","genérico"];
const letras9 = ["perspicaz","recíproco","concessão","impressão","escrúpulo","supérfluo","retificar","paradigma","dicotomia","propósito","presunção","concepção","hipócrita","ratificar","implícito","plenitude","essencial","hegemonia","corolário","incidente","esdrúxulo","altruísmo","vagabundo","altruísta","hermético","aleatório","esperança","promíscuo","persuadir","confiança","deliberar","sapiência","indelével","demasiado","mesquinho","diligente","impetuoso","descrição","regozijar","resignado","inusitado","eminência","compaixão","prudência","pretensão","discrição","analítico","explícito","ordinário","percepção","exequível","nostalgia","subjetivo","autonomia","autóctone","companhia","resolução","desdenhar","fidedigno","dissensão","expressão","constante","supressão","taciturno","imparcial","autêntico","paciência","ignorante","arrogante","outrossim","execrável","discorrer","desumilde","restrição","obstinado","consoante","jactância","arcabouço","cognitivo","adjacente","eloquente","instância","interesse","limítrofe","sintético","iminência","submissão","presságio","relevante","irascível","empecilho","excelente","liberdade","ludibriar","aquisição","humildade","ambicioso","plausível","convicção","primícias"];
const letras10 = ["dicionário","intrínseco","prescindir","presunçoso","diligência","corroborar","intempérie","detrimento","maturidade","parcimônia","referência","inspiração","inexorável","pragmático","prepotente","incipiente","disruptivo","sororidade","serenidade","arbitrário","indulgente","auspicioso","iniquidade","pertinente","sagacidade","resignação","hipocrisia","preconizar","precedente","vislumbrar","incidência","lisonjeado","suscetível","entretanto","disposição","excêntrico","subestimar","preliminar","tribulação","depreender","fleumático","anacrônico","equivocado","escrutínio","retrógrado","indolência","excelência","ingerência","democracia","infortúnio","compassivo","contemplar","importante","pejorativo","restringir","sintetizar","proposição","primordial","signatário","conjuntura","coercitivo","intrínseca","dissolução","subjacente","itinerário","finalidade","esplêndido","alteridade","pecuniária","espontâneo","designação","transeunte","necessário","constância","sarcástico","pusilânime","privilégio","idoneidade","desprovido","verossímil","pernóstico","exacerbado","felicidade","relevância","divergente","disciplina","inferência","pernicioso","disseminar","satisfação","reverberar","meticuloso","esporádico","influência","militância","retumbante","consolidar","fornicação","subversivo"];
const letras11 = ["significado","perspectiva","resiliência","dissimulado","vicissitude","complacente","contundente","peremptório","comorbidade","compreensão","perspicácia","expectativa","pressuposto","beneplácito","subterfúgio","preconceito","experiência","indiferente","consonância","pretensioso","transcender","imensurável","intensidade","contingente","beligerante","proeminente","necessidade","superficial","concernente","benignidade","contencioso","inenarrável","animosidade","intervenção","incumbência","vocabulário","antagonismo","cumprimento","resistência","indiferença","reivindicar","compreender","supracitado","subsequente","estereótipo","integridade","diversidade","ambiguidade","deliberação","especulação","indulgência","proveniente","divergência","elucubração","indubitável","austeridade","prognóstico","importância","heterogêneo","tergiversar","benevolente","displicente","negligência","oportunista","identificar","estabelecer","conveniente","redundância","congruência","discriminar","consciência","substantivo","pragmatismo","providência","excepcional","admoestação","conferência","facultativo","sistemático","compulsório","comprimento","verborragia","intersecção","subordinado","intelectual","melancólico","contradição","relativizar","generalizar","desenvolver","substancial","honestidade","dificuldade","retificação","conservador","procedência","autoritário","amabilidade","determinado","antagonista"];
const letras12 = ["perseverança","condolências","remanescente","prerrogativa","extrovertido","complacência","procrastinar","discrepância","determinação","independente","consequência","intermitente","conveniência","benevolência","compartilhar","eclesiástico","contingência","transgressão","felicitações","consideração","concomitante","convergência","cordialidade","conhecimento","cumplicidade","convencional","subsistência","disseminação","proselitismo","sistematizar","complexidade","coincidência","prescindível","controvérsia","imprevisível","impertinente","inverossímil","escatológico","displicência","interlocutor","libertinagem","ninfomaníaco","conformidade","proporcionar","intempestivo","maledicência","extemporâneo","fraternidade","intolerância","resplandecer","perseverante","misericórdia","estabilidade","mediocridade","persistência","coexistência","maquiavélico","circunspecto","preeminência","aquiescência","hermenêutica","protagonista","complementar","parcialmente","proeminência","introvertido","consolidação","oportunidade","constituição","destinatário","escarnecedor","deslumbrante","estigmatizar","consistência","parcialidade","entendimento","interessante","caracterizar","incircunciso","procedimento","generosidade","condicionado","circuncidado","enclausurado","superestimar","fragmentação","literalmente","desenvoltura","proficiência","prosperidade","depreciativo","legitimidade","simplicidade","profissional","incolumidade","ininterrupto","sobremaneira","inescrutável","beneficência"];
const letras13 = ["reciprocidade","contemporâneo","inconveniente","heterossexual","circunstância","discernimento","solidariedade","promiscuidade","ressignificar","intransigente","credibilidade","discriminação","transcendente","aprovisionado","epistemologia","contrapartida","assintomático","comprobatório","perpendicular","incongruência","reminiscência","ressentimento","estereotipado","possibilidade","recenseamento","intermediário","veementemente","preponderante","indispensável","subjetividade","hodiernamente","singularidade","subserviência","longanimidade","convalescença","pormenorizado","autenticidade","transformação","independência","incontinência","instabilidade","superveniente","sensibilidade","introspectivo","reivindicação","elegibilidade","superestimado","contraditório","indissociável","multifacetado","latifundiário","eventualmente","recalcitrante","desmistificar","incredulidade","quintessência","inconsequente","sobressalente","ininteligível","inescrupuloso","comportamento","personalidade","indescritível","integralmente","implementação","monossilábico","homogeneidade","magnificência","provavelmente","precipuamente","peculiaridade","circunscrição","consentimento","incondicional","convalescente","remanejamento","serendipidade","contentamento","consciencioso","correlacionar","arrefecimento","incandescente","predisposição","versatilidade","conscientizar","desnecessário","irresponsável","supersticioso","indeterminado","imperceptível","representação","especificação","identificação","reconciliação","incognoscível","ressarcimento","receptividade","monocromático"];
const letras14 = ["imprescindível","condescendente","idiossincrasia","característica","concupiscência","extraordinário","demasiadamente","intercorrência","irrepreensível","consubstanciar","incomensurável","discricionário","preponderância","arbitrariedade","especificidade","posteriormente","imprescritível","intransponível","contextualizar","empreendimento","ancestralidade","entretenimento","transcendental","paulatinamente","infraestrutura","relacionamento","arrependimento","revolucionário","imparcialidade","superveniência","atenciosamente","transcendência","periodicamente","reconhecimento","democratização","insignificante","diligentemente","inconsistência","personificação","despretensioso","impessoalidade","socioambiental","espontaneidade","funcionalidade","intransigência","aplicabilidade","desprendimento","procrastinação","principalmente","potencialidade","estelionatário","procrastinador","estratificação","licenciosidade","extraordinária","excentricidade","prestatividade","inconveniência","dissolutamente","congratulações","pusilanimidade","exequibilidade","epistemológico","insubstituível","individualismo","biodiversidade","resplandecente","jurisprudência","abundantemente","coercitividade","disponibilizar","plausibilidade","acessibilidade","internalização","credenciamento","papibaquígrafo","constantemente","exclusivamente","perfeccionista","multiplicidade","aleatoriamente","impressionante","questionamento","implicitamente","grandiloquente","esclarecimento","minuciosamente","permissividade","frequentemente","indiscriminado","intermunicipal","concessionária","sobrecarregado","transfiguração"];

let dicionario = [];
dicionario = dicionario.concat(letras3,letras4,letras5,letras6,letras7,letras8,letras9,letras10,letras11,letras12,letras13,letras14);
const palavraSecreta = dicionario[Math.trunc(Math.random()*dicionario.length)];
const palavraSecretaSemAcentos = tirarAcentos(palavraSecreta);
for (let i=palavraSecreta.length;i<14;i++){
document.getElementsByClassName("cabecalho")[i].setAttribute("style","display: none");
}
let tentativas = 10;
let letrasRestantes = palavraSecreta.length;
document.getElementById("cabecalho2").innerHTML = "( "+palavraSecreta.length+" letras)";
document.getElementsByTagName("h1")[1].innerHTML = `${tentativas}`;